### ISSUE TITLE
정실 소개 페이지

### ISSUE THREAD

**Issue by ktwin01** [GSAlgo/BasisForGSAlgo#12]
하나 만들고 싶어요.... 아이디어 있는 사람?

**Comment by genie5741** [comment]
만들었습니다.
근데 readme 파일은 홈페이지에 안올릴꺼죠?

**Comment by ktwin01** [comment]
음.... 안올릴꺼임 올리리면 깃헙에서 테이블 표시되서 귀차늠

**Comment by genie5741** [comment]
https://gsalgo.github.io/BasisForGSAlgo/GSAlgo/
