### ISSUE TITLE
category title blank issue

### ISSUE THREAD

**Issue by genie5741** [GSAlgo/BasisForGSAlgo#23]
응급처치로 category의 md파일들에 nbtitle(기존 title에서 공백만 제거)를 생성하여서 _layouts의 category.html을 수정하였더니
![image](https://user-images.githubusercontent.com/34810033/80232479-f198f500-868f-11ea-86d9-bd8d3baa4111.png)
이렇게 공백이 없는 것이 출력되는 버그가 생겨버렸습니다.
도와주세요 재윤님

**Comment by ktwin01** [comment]
Woojin, actually your commit was wrong;
when you post your categories field should type like this
`categories: [Data Structure]`
So actually there are no needs for using nbcategories..

So I revert it and fix your problems...

next time plz add Issue and fix together...;;;;;
