### ISSUE TITLE
Categories name...

### ISSUE THREAD

**Issue by ktwin01** [GSAlgo/BasisForGSAlgo#25]
I think commit about folder name(no blank) forgot to add programming;;;;; my posts are not shown in site

**Comment by genie5741** [comment]
nooo

**Comment by genie5741** [comment]
fixed it. I forgot the category 'programming'

**Comment by ktwin01** [comment]
actually your commit was no needed....

plz See **[issue#23](https://github.com/GSAlgo/BasisForGSAlgo/issues/23)**
